// src/lib/emojiData.ts
export interface EmojiEntry {
  char: string;
  name: string; // used for search
}

export interface EmojiCategory {
  key: string;
  label: string;
  emojis: EmojiEntry[];
}

// Fallback set when the user has fewer than 12 tracked emojis — mirrors
// common WhatsApp/iMessage quick-reaction defaults.
export const DEFAULT_TOP_EMOJIS: string[] = [
  "👍", "❤️", "😂", "😮", "😢", "🙏",
  "🔥", "🎉", "👏", "😍", "😅", "🤝",
];

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    key: "smileys",
    label: "Smileys & People",
    emojis: [
      { char: "😀", name: "grinning face" },
      { char: "😃", name: "grinning face big eyes" },
      { char: "😄", name: "smiling face open mouth" },
      { char: "😁", name: "beaming face" },
      { char: "😆", name: "grinning squinting" },
      { char: "😅", name: "sweat smile" },
      { char: "🤣", name: "rolling on floor laughing" },
      { char: "😂", name: "face with tears of joy" },
      { char: "🙂", name: "slightly smiling face" },
      { char: "🙃", name: "upside down face" },
      { char: "😉", name: "winking face" },
      { char: "😊", name: "smiling face" },
      { char: "😇", name: "angel halo" },
      { char: "😍", name: "heart eyes" },
      { char: "🥰", name: "smiling face with hearts" },
      { char: "😘", name: "face blowing kiss" },
      { char: "😗", name: "kissing face" },
      { char: "😋", name: "yum" },
      { char: "😛", name: "tongue out" },
      { char: "😜", name: "winking tongue" },
      { char: "🤪", name: "zany face" },
      { char: "😝", name: "squinting tongue" },
      { char: "🤑", name: "money mouth" },
      { char: "🤗", name: "hugging face" },
      { char: "🤭", name: "hand over mouth" },
      { char: "🤫", name: "shushing face" },
      { char: "🤔", name: "thinking face" },
      { char: "🤨", name: "raised eyebrow" },
      { char: "😐", name: "neutral face" },
      { char: "😑", name: "expressionless" },
      { char: "😶", name: "no mouth" },
      { char: "😏", name: "smirking face" },
      { char: "😒", name: "unamused" },
      { char: "🙄", name: "eye roll" },
      { char: "😬", name: "grimacing" },
      { char: "😌", name: "relieved" },
      { char: "😔", name: "pensive" },
      { char: "😪", name: "sleepy" },
      { char: "🤤", name: "drooling" },
      { char: "😴", name: "sleeping" },
      { char: "😷", name: "medical mask" },
      { char: "🤒", name: "thermometer face" },
      { char: "🤕", name: "head bandage" },
      { char: "🤢", name: "nauseated" },
      { char: "🤮", name: "vomiting" },
      { char: "🥵", name: "hot face" },
      { char: "🥶", name: "cold face" },
      { char: "😵", name: "dizzy face" },
      { char: "🤯", name: "exploding head" },
      { char: "🥳", name: "party face" },
      { char: "😎", name: "sunglasses" },
      { char: "🤓", name: "nerd face" },
      { char: "🧐", name: "monocle face" },
      { char: "😕", name: "confused" },
      { char: "😟", name: "worried" },
      { char: "🙁", name: "slightly frowning" },
      { char: "😮", name: "open mouth" },
      { char: "😯", name: "hushed" },
      { char: "😲", name: "astonished" },
      { char: "😳", name: "flushed" },
      { char: "🥺", name: "pleading face" },
      { char: "😦", name: "frowning open mouth" },
      { char: "😧", name: "anguished" },
      { char: "😨", name: "fearful" },
      { char: "😰", name: "anxious sweat" },
      { char: "😥", name: "sad relieved" },
      { char: "😢", name: "crying face" },
      { char: "😭", name: "loudly crying" },
      { char: "😱", name: "screaming fear" },
      { char: "😖", name: "confounded" },
      { char: "😣", name: "persevering" },
      { char: "😞", name: "disappointed" },
      { char: "😓", name: "downcast sweat" },
      { char: "😩", name: "weary" },
      { char: "😫", name: "tired face" },
      { char: "🥱", name: "yawning" },
      { char: "😤", name: "triumph" },
      { char: "😡", name: "pouting angry" },
      { char: "😠", name: "angry face" },
      { char: "🤬", name: "cursing face" },
      { char: "😈", name: "smiling devil" },
      { char: "👿", name: "angry devil" },
      { char: "💀", name: "skull" },
      { char: "☠️", name: "skull crossbones" },
      { char: "🤡", name: "clown face" },
      { char: "👻", name: "ghost" },
      { char: "👽", name: "alien" },
    ],
  },
  {
    key: "gestures",
    label: "Gestures & Body",
    emojis: [
      { char: "👍", name: "thumbs up" },
      { char: "👎", name: "thumbs down" },
      { char: "👏", name: "clapping hands" },
      { char: "🙌", name: "raised hands" },
      { char: "👐", name: "open hands" },
      { char: "🤝", name: "handshake" },
      { char: "🙏", name: "folded hands pray" },
      { char: "✌️", name: "victory peace" },
      { char: "🤞", name: "fingers crossed" },
      { char: "👌", name: "ok hand" },
      { char: "🤌", name: "pinched fingers" },
      { char: "👊", name: "fist bump" },
      { char: "✊", name: "raised fist" },
      { char: "🤛", name: "left fist" },
      { char: "🤜", name: "right fist" },
      { char: "💪", name: "flexed biceps muscle" },
      { char: "🖐️", name: "raised hand fingers" },
      { char: "✋", name: "raised hand" },
      { char: "👋", name: "waving hand" },
      { char: "🤟", name: "love you gesture" },
      { char: "🤘", name: "rock on" },
      { char: "👉", name: "pointing right" },
      { char: "👈", name: "pointing left" },
      { char: "👆", name: "pointing up" },
      { char: "👇", name: "pointing down" },
      { char: "☝️", name: "index pointing up" },
      { char: "✍️", name: "writing hand" },
      { char: "💅", name: "nail polish" },
      { char: "👀", name: "eyes" },
      { char: "👁️", name: "eye" },
      { char: "🧠", name: "brain" },
    ],
  },
  {
    key: "hearts",
    label: "Hearts",
    emojis: [
      { char: "❤️", name: "red heart" },
      { char: "🧡", name: "orange heart" },
      { char: "💛", name: "yellow heart" },
      { char: "💚", name: "green heart" },
      { char: "💙", name: "blue heart" },
      { char: "💜", name: "purple heart" },
      { char: "🖤", name: "black heart" },
      { char: "🤍", name: "white heart" },
      { char: "🤎", name: "brown heart" },
      { char: "💔", name: "broken heart" },
      { char: "❣️", name: "heart exclamation" },
      { char: "💕", name: "two hearts" },
      { char: "💞", name: "revolving hearts" },
      { char: "💓", name: "beating heart" },
      { char: "💗", name: "growing heart" },
      { char: "💖", name: "sparkling heart" },
      { char: "💘", name: "heart with arrow" },
      { char: "💝", name: "heart with ribbon" },
    ],
  },
  {
    key: "animals",
    label: "Animals & Nature",
    emojis: [
      { char: "🐶", name: "dog face" },
      { char: "🐱", name: "cat face" },
      { char: "🐭", name: "mouse face" },
      { char: "🐹", name: "hamster" },
      { char: "🐰", name: "rabbit face" },
      { char: "🦊", name: "fox" },
      { char: "🐻", name: "bear" },
      { char: "🐼", name: "panda" },
      { char: "🐨", name: "koala" },
      { char: "🐯", name: "tiger face" },
      { char: "🦁", name: "lion" },
      { char: "🐮", name: "cow face" },
      { char: "🐷", name: "pig face" },
      { char: "🐸", name: "frog" },
      { char: "🐵", name: "monkey face" },
      { char: "🙈", name: "see no evil monkey" },
      { char: "🙉", name: "hear no evil monkey" },
      { char: "🙊", name: "speak no evil monkey" },
      { char: "🐔", name: "chicken" },
      { char: "🐧", name: "penguin" },
      { char: "🐦", name: "bird" },
      { char: "🦅", name: "eagle" },
      { char: "🦉", name: "owl" },
      { char: "🐴", name: "horse face" },
      { char: "🦄", name: "unicorn" },
      { char: "🐝", name: "honeybee" },
      { char: "🦋", name: "butterfly" },
      { char: "🐢", name: "turtle" },
      { char: "🐍", name: "snake" },
      { char: "🐙", name: "octopus" },
      { char: "🌸", name: "cherry blossom" },
      { char: "🌹", name: "rose" },
      { char: "🌻", name: "sunflower" },
      { char: "🌴", name: "palm tree" },
      { char: "🌵", name: "cactus" },
      { char: "🍀", name: "four leaf clover" },
      { char: "🌈", name: "rainbow" },
      { char: "☀️", name: "sun" },
      { char: "⭐", name: "star" },
      { char: "🌙", name: "crescent moon" },
    ],
  },
  {
    key: "food",
    label: "Food & Drink",
    emojis: [
      { char: "🍎", name: "red apple" },
      { char: "🍌", name: "banana" },
      { char: "🍇", name: "grapes" },
      { char: "🍓", name: "strawberry" },
      { char: "🍉", name: "watermelon" },
      { char: "🍍", name: "pineapple" },
      { char: "🥭", name: "mango" },
      { char: "🍑", name: "peach" },
      { char: "🍕", name: "pizza" },
      { char: "🍔", name: "hamburger" },
      { char: "🍟", name: "fries" },
      { char: "🌭", name: "hot dog" },
      { char: "🌮", name: "taco" },
      { char: "🍗", name: "chicken leg" },
      { char: "🍖", name: "meat on bone" },
      { char: "🍳", name: "fried egg" },
      { char: "🍚", name: "rice" },
      { char: "🍜", name: "noodles" },
      { char: "🍲", name: "pot of food" },
      { char: "🍤", name: "fried shrimp" },
      { char: "🍦", name: "soft ice cream" },
      { char: "🎂", name: "birthday cake" },
      { char: "🍩", name: "doughnut" },
      { char: "🍪", name: "cookie" },
      { char: "🍫", name: "chocolate bar" },
      { char: "🍿", name: "popcorn" },
      { char: "☕", name: "coffee" },
      { char: "🍵", name: "tea" },
      { char: "🍺", name: "beer" },
      { char: "🍷", name: "wine glass" },
      { char: "🥂", name: "clinking glasses" },
      { char: "🍾", name: "champagne bottle" },
    ],
  },
  {
    key: "activities",
    label: "Activities",
    emojis: [
      { char: "⚽", name: "soccer ball" },
      { char: "🏀", name: "basketball" },
      { char: "🏈", name: "american football" },
      { char: "⚾", name: "baseball" },
      { char: "🎾", name: "tennis" },
      { char: "🏐", name: "volleyball" },
      { char: "🎱", name: "8 ball" },
      { char: "🏓", name: "ping pong" },
      { char: "🎯", name: "dart target" },
      { char: "🎮", name: "video game" },
      { char: "🎲", name: "dice" },
      { char: "🎸", name: "guitar" },
      { char: "🎹", name: "piano" },
      { char: "🎤", name: "microphone" },
      { char: "🎧", name: "headphones" },
      { char: "🎬", name: "clapperboard movie" },
      { char: "🎨", name: "artist palette" },
      { char: "🏆", name: "trophy" },
      { char: "🥇", name: "gold medal" },
      { char: "🎉", name: "party popper" },
      { char: "🎊", name: "confetti ball" },
      { char: "🎁", name: "wrapped gift" },
      { char: "🎈", name: "balloon" },
    ],
  },
  {
    key: "objects",
    label: "Objects",
    emojis: [
      { char: "📱", name: "mobile phone" },
      { char: "💻", name: "laptop" },
      { char: "⌚", name: "watch" },
      { char: "📷", name: "camera" },
      { char: "🔦", name: "flashlight" },
      { char: "💡", name: "light bulb" },
      { char: "🔋", name: "battery" },
      { char: "💰", name: "money bag" },
      { char: "💵", name: "dollar banknote" },
      { char: "💳", name: "credit card" },
      { char: "📦", name: "package box" },
      { char: "📌", name: "pushpin" },
      { char: "📍", name: "round pushpin" },
      { char: "🔒", name: "locked" },
      { char: "🔑", name: "key" },
      { char: "🔨", name: "hammer" },
      { char: "⚙️", name: "gear" },
      { char: "🧵", name: "thread" },
      { char: "💊", name: "pill" },
      { char: "🎓", name: "graduation cap" },
      { char: "📚", name: "books" },
      { char: "✏️", name: "pencil" },
      { char: "📝", name: "memo notes" },
    ],
  },
  {
    key: "symbols",
    label: "Symbols",
    emojis: [
      { char: "✅", name: "check mark" },
      { char: "❌", name: "cross mark" },
      { char: "❓", name: "question mark" },
      { char: "❗", name: "exclamation mark" },
      { char: "‼️", name: "double exclamation" },
      { char: "💯", name: "hundred points" },
      { char: "🔥", name: "fire" },
      { char: "✨", name: "sparkles" },
      { char: "⚡", name: "lightning bolt" },
      { char: "💥", name: "collision boom" },
      { char: "💫", name: "dizzy stars" },
      { char: "💤", name: "zzz sleep" },
      { char: "🔴", name: "red circle" },
      { char: "🟢", name: "green circle" },
      { char: "🔵", name: "blue circle" },
      { char: "⚠️", name: "warning" },
      { char: "🚫", name: "prohibited" },
      { char: "♻️", name: "recycle" },
      { char: "🆗", name: "ok button" },
      { char: "🆕", name: "new button" },
    ],
  },
];

export function searchEmojis(query: string): EmojiEntry[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const results: EmojiEntry[] = [];
  for (const category of EMOJI_CATEGORIES) {
    for (const entry of category.emojis) {
      if (entry.name.includes(q)) results.push(entry);
    }
  }
  return results;
      }
