// src/lib/sounds.ts
//
// Central registry of every sound event Ako can play, grouped into a small
// set of "families" so the app has one cohesive sonic voice instead of a
// one-off effect per action. See useSound.tsx for playback + settings.
//
// Placeholder audio lives in public/sounds/ — plain synthesized tones,
// generated by scripts/generate_placeholder_sounds.py, standing in until
// real sound design is dropped in under the same filenames.

export type SoundFamily = "confirm" | "notification" | "reward" | "alert" | "presence";

export type SoundEvent =
  | "message-sent"
  | "message-received"
  | "notification-generic"
  | "like"
  | "follow"
  | "gift-sent"
  | "gift-received"
  | "unlock-success"
  | "error"
  | "room-join"
  | "room-leave";

interface SoundDef {
  /** Bundled asset (require() result), played through expo-audio. */
  source: number;
  family: SoundFamily;
  description: string;
}

export const SOUND_REGISTRY: Record<SoundEvent, SoundDef> = {
  "message-sent": {
    source: require("../../assets/sounds/confirm-message-sent.wav"),
    family: "confirm",
    description: "A message you sent left successfully.",
  },
  "message-received": {
    source: require("../../assets/sounds/notification-message-received.wav"),
    family: "notification",
    description: "A new message arrived while the app is open.",
  },
  "notification-generic": {
    source: require("../../assets/sounds/notification-generic.wav"),
    family: "notification",
    description: "Mentions, comments, new followers — the catch-all bell.",
  },
  like: {
    source: require("../../assets/sounds/confirm-like.wav"),
    family: "confirm",
    description: "You liked a post.",
  },
  follow: {
    source: require("../../assets/sounds/confirm-follow.wav"),
    family: "confirm",
    description: "You followed someone.",
  },
  "gift-sent": {
    source: require("../../assets/sounds/reward-gift-sent.wav"),
    family: "reward",
    description: "A gift you sent went through.",
  },
  "gift-received": {
    source: require("../../assets/sounds/reward-gift-received.wav"),
    family: "reward",
    description: "Someone sent you a gift.",
  },
  "unlock-success": {
    source: require("../../assets/sounds/reward-unlock-success.wav"),
    family: "reward",
    description: "A project, ticket, or course purchase/unlock succeeded.",
  },
  error: {
    source: require("../../assets/sounds/alert-error.wav"),
    family: "alert",
    description: "A payment or other important action failed.",
  },
  "room-join": {
    source: require("../../assets/sounds/presence-join.wav"),
    family: "presence",
    description: "You joined a live Room or Meeting.",
  },
  "room-leave": {
    source: require("../../assets/sounds/presence-leave.wav"),
    family: "presence",
    description: "You left a live Room or Meeting.",
  },
};

// Minimalist mode plays fewer events rather than plainer versions of all of
// them — only the moments with real stakes (a reward landing, a message
// arriving, something failing). Confirm taps (like, follow, message-sent)
// and ambient presence cues (room join/leave) are flourish and go quiet.
export const MINIMALIST_EVENTS: ReadonlySet<SoundEvent> = new Set([
  "message-received",
  "notification-generic",
  "gift-received",
  "unlock-success",
  "error",
]);

// System-level vs. in-app-only — worth encoding now even though it does
// nothing until the app is wrapped natively. Once that happens,
// "system" events should defer to the OS/user-selected tone (their chosen
// ringtone or the phone's default notification sound) instead of playing
// our own file; "in-app" events have no OS equivalent and always stay
// custom.
export const SYSTEM_LEVEL_EVENTS: ReadonlySet<SoundEvent> = new Set([
  "message-received",
  "notification-generic",
]);
